/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface AnomalyDetectionData
 */
export interface AnomalyDetectionData {
    /**
     * 
     * @type {string}
     * @memberof AnomalyDetectionData
     */
    'encounterId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnomalyDetectionData
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnomalyDetectionData
     */
    'dataAccessPattern'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof AnomalyDetectionData
     */
    'timeStamp'?: Timestamp;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnomalyDetectionData
     */
    'anomaliesDetected'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AnomalyDetectionData
     */
    'sourceIp'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnomalyDetectionData
     */
    'location'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnomalyDetectionData
     */
    'affectedSystems'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AnomalyDetectionData
     */
    'severityLevel'?: string;
}

