/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthorizationControlData
 */
export interface AuthorizationControlData {
    /**
     * 
     * @type {string}
     * @memberof AuthorizationControlData
     */
    'encounterId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationControlData
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationControlData
     */
    'dataAccessLevel'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationControlData
     */
    'accessGrantedBy'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthorizationControlData
     */
    'accessScopes'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationControlData
     */
    'accessValidityPeriod'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthorizationControlData
     */
    'isTemporaryAccess'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthorizationControlData
     */
    'conditionalAccessParams'?: Array<string>;
}

