/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { EmailAddress } from './email-address';
// May contain unused imports in some cases
// @ts-ignore
import type { FullName } from './full-name';
// May contain unused imports in some cases
// @ts-ignore
import type { PhoneNumber } from './phone-number';

/**
 * 
 * @export
 * @interface ContactInfo
 */
export interface ContactInfo {
    /**
     * 
     * @type {FullName}
     * @memberof ContactInfo
     */
    'name'?: FullName;
    /**
     * 
     * @type {string}
     * @memberof ContactInfo
     */
    'patientId'?: string;
    /**
     * 
     * @type {Array<Address>}
     * @memberof ContactInfo
     */
    'addresses'?: Array<Address>;
    /**
     * 
     * @type {Array<PhoneNumber>}
     * @memberof ContactInfo
     */
    'phoneNumbers'?: Array<PhoneNumber>;
    /**
     * 
     * @type {Array<EmailAddress>}
     * @memberof ContactInfo
     */
    'emails'?: Array<EmailAddress>;
}

