/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PhoneNumber
 */
export interface PhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof PhoneNumber
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof PhoneNumber
     */
    'type'?: PhoneType;
}

export const PhoneType = {
    PhoneTypeNotSpecified: 'PHONE_TYPE_NOT_SPECIFIED',
    PhoneTypeMobile: 'PHONE_TYPE_MOBILE',
    PhoneTypeHome: 'PHONE_TYPE_HOME',
    PhoneTypeWork: 'PHONE_TYPE_WORK',
    PhoneTypeFax: 'PHONE_TYPE_FAX',
    PhoneTypeOther: 'PHONE_TYPE_OTHER',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type PhoneType = typeof PhoneType[keyof typeof PhoneType];


