/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface RealTimeMonitoringData
 */
export interface RealTimeMonitoringData {
    /**
     * 
     * @type {string}
     * @memberof RealTimeMonitoringData
     */
    'encounterId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RealTimeMonitoringData
     */
    'monitoredEntity'?: string;
    /**
     * 
     * @type {string}
     * @memberof RealTimeMonitoringData
     */
    'monitoringDetails'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof RealTimeMonitoringData
     */
    'monitoringStartTime'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof RealTimeMonitoringData
     */
    'monitoringEndTime'?: Timestamp;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealTimeMonitoringData
     */
    'triggeredAlerts'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RealTimeMonitoringData
     */
    'monitoringFrequency'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RealTimeMonitoringData
     */
    'isContinuousMonitoring'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RealTimeMonitoringData
     */
    'responsibleMonitoringTeam'?: string;
}

