/* tslint:disable */
/* eslint-disable */
/**
 * Profile API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileRequestUpdatedProfileEmailInner
 */
export interface UpdateProfileRequestUpdatedProfileEmailInner {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfileEmailInner
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfileEmailInner
     */
    type?: string;
}

/**
 * Check if a given object implements the UpdateProfileRequestUpdatedProfileEmailInner interface.
 */
export function instanceOfUpdateProfileRequestUpdatedProfileEmailInner(value: object): value is UpdateProfileRequestUpdatedProfileEmailInner {
    return true;
}

export function UpdateProfileRequestUpdatedProfileEmailInnerFromJSON(json: any): UpdateProfileRequestUpdatedProfileEmailInner {
    return UpdateProfileRequestUpdatedProfileEmailInnerFromJSONTyped(json, false);
}

export function UpdateProfileRequestUpdatedProfileEmailInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequestUpdatedProfileEmailInner {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function UpdateProfileRequestUpdatedProfileEmailInnerToJSON(value?: UpdateProfileRequestUpdatedProfileEmailInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'type': value['type'],
    };
}

