/* tslint:disable */
/* eslint-disable */
/**
 * Profile API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateProfileRequestUpdatedProfileDateOfBirth } from './UpdateProfileRequestUpdatedProfileDateOfBirth';
import {
    UpdateProfileRequestUpdatedProfileDateOfBirthFromJSON,
    UpdateProfileRequestUpdatedProfileDateOfBirthFromJSONTyped,
    UpdateProfileRequestUpdatedProfileDateOfBirthToJSON,
} from './UpdateProfileRequestUpdatedProfileDateOfBirth';
import type { UpdateProfileRequestUpdatedProfileFullName } from './UpdateProfileRequestUpdatedProfileFullName';
import {
    UpdateProfileRequestUpdatedProfileFullNameFromJSON,
    UpdateProfileRequestUpdatedProfileFullNameFromJSONTyped,
    UpdateProfileRequestUpdatedProfileFullNameToJSON,
} from './UpdateProfileRequestUpdatedProfileFullName';
import type { UpdateProfileRequestUpdatedProfilePhoneInner } from './UpdateProfileRequestUpdatedProfilePhoneInner';
import {
    UpdateProfileRequestUpdatedProfilePhoneInnerFromJSON,
    UpdateProfileRequestUpdatedProfilePhoneInnerFromJSONTyped,
    UpdateProfileRequestUpdatedProfilePhoneInnerToJSON,
} from './UpdateProfileRequestUpdatedProfilePhoneInner';
import type { UpdateProfileRequestUpdatedProfileEmailInner } from './UpdateProfileRequestUpdatedProfileEmailInner';
import {
    UpdateProfileRequestUpdatedProfileEmailInnerFromJSON,
    UpdateProfileRequestUpdatedProfileEmailInnerFromJSONTyped,
    UpdateProfileRequestUpdatedProfileEmailInnerToJSON,
} from './UpdateProfileRequestUpdatedProfileEmailInner';

/**
 * 
 * @export
 * @interface UpdateProfileRequestUpdatedProfile
 */
export interface UpdateProfileRequestUpdatedProfile {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfile
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfile
     */
    nationalHealthId?: string;
    /**
     * 
     * @type {UpdateProfileRequestUpdatedProfileFullName}
     * @memberof UpdateProfileRequestUpdatedProfile
     */
    fullName?: UpdateProfileRequestUpdatedProfileFullName;
    /**
     * 
     * @type {UpdateProfileRequestUpdatedProfileDateOfBirth}
     * @memberof UpdateProfileRequestUpdatedProfile
     */
    dateOfBirth?: UpdateProfileRequestUpdatedProfileDateOfBirth;
    /**
     * 
     * @type {Array<UpdateProfileRequestUpdatedProfileEmailInner>}
     * @memberof UpdateProfileRequestUpdatedProfile
     */
    email?: Array<UpdateProfileRequestUpdatedProfileEmailInner>;
    /**
     * 
     * @type {Array<UpdateProfileRequestUpdatedProfilePhoneInner>}
     * @memberof UpdateProfileRequestUpdatedProfile
     */
    phone?: Array<UpdateProfileRequestUpdatedProfilePhoneInner>;
}

/**
 * Check if a given object implements the UpdateProfileRequestUpdatedProfile interface.
 */
export function instanceOfUpdateProfileRequestUpdatedProfile(value: object): value is UpdateProfileRequestUpdatedProfile {
    return true;
}

export function UpdateProfileRequestUpdatedProfileFromJSON(json: any): UpdateProfileRequestUpdatedProfile {
    return UpdateProfileRequestUpdatedProfileFromJSONTyped(json, false);
}

export function UpdateProfileRequestUpdatedProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequestUpdatedProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'nationalHealthId': json['nationalHealthId'] == null ? undefined : json['nationalHealthId'],
        'fullName': json['fullName'] == null ? undefined : UpdateProfileRequestUpdatedProfileFullNameFromJSON(json['fullName']),
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : UpdateProfileRequestUpdatedProfileDateOfBirthFromJSON(json['dateOfBirth']),
        'email': json['email'] == null ? undefined : ((json['email'] as Array<any>).map(UpdateProfileRequestUpdatedProfileEmailInnerFromJSON)),
        'phone': json['phone'] == null ? undefined : ((json['phone'] as Array<any>).map(UpdateProfileRequestUpdatedProfilePhoneInnerFromJSON)),
    };
}

export function UpdateProfileRequestUpdatedProfileToJSON(value?: UpdateProfileRequestUpdatedProfile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'nationalHealthId': value['nationalHealthId'],
        'fullName': UpdateProfileRequestUpdatedProfileFullNameToJSON(value['fullName']),
        'dateOfBirth': UpdateProfileRequestUpdatedProfileDateOfBirthToJSON(value['dateOfBirth']),
        'email': value['email'] == null ? undefined : ((value['email'] as Array<any>).map(UpdateProfileRequestUpdatedProfileEmailInnerToJSON)),
        'phone': value['phone'] == null ? undefined : ((value['phone'] as Array<any>).map(UpdateProfileRequestUpdatedProfilePhoneInnerToJSON)),
    };
}

