/* tslint:disable */
/* eslint-disable */
/**
 * Profile API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileRequestUpdatedProfileFullName
 */
export interface UpdateProfileRequestUpdatedProfileFullName {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfileFullName
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfileFullName
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfileFullName
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfileFullName
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfileFullName
     */
    suffix?: string;
}

/**
 * Check if a given object implements the UpdateProfileRequestUpdatedProfileFullName interface.
 */
export function instanceOfUpdateProfileRequestUpdatedProfileFullName(value: object): value is UpdateProfileRequestUpdatedProfileFullName {
    return true;
}

export function UpdateProfileRequestUpdatedProfileFullNameFromJSON(json: any): UpdateProfileRequestUpdatedProfileFullName {
    return UpdateProfileRequestUpdatedProfileFullNameFromJSONTyped(json, false);
}

export function UpdateProfileRequestUpdatedProfileFullNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequestUpdatedProfileFullName {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
    };
}

export function UpdateProfileRequestUpdatedProfileFullNameToJSON(value?: UpdateProfileRequestUpdatedProfileFullName | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'firstName': value['firstName'],
        'middleName': value['middleName'],
        'lastName': value['lastName'],
        'suffix': value['suffix'],
    };
}

