/* tslint:disable */
/* eslint-disable */
/**
 * Profile API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileRequestUpdatedProfilePhoneInner
 */
export interface UpdateProfileRequestUpdatedProfilePhoneInner {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfilePhoneInner
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequestUpdatedProfilePhoneInner
     */
    type?: string;
}

/**
 * Check if a given object implements the UpdateProfileRequestUpdatedProfilePhoneInner interface.
 */
export function instanceOfUpdateProfileRequestUpdatedProfilePhoneInner(value: object): value is UpdateProfileRequestUpdatedProfilePhoneInner {
    return true;
}

export function UpdateProfileRequestUpdatedProfilePhoneInnerFromJSON(json: any): UpdateProfileRequestUpdatedProfilePhoneInner {
    return UpdateProfileRequestUpdatedProfilePhoneInnerFromJSONTyped(json, false);
}

export function UpdateProfileRequestUpdatedProfilePhoneInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequestUpdatedProfilePhoneInner {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function UpdateProfileRequestUpdatedProfilePhoneInnerToJSON(value?: UpdateProfileRequestUpdatedProfilePhoneInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'number': value['number'],
        'type': value['type'],
    };
}

