/* tslint:disable */
/* eslint-disable */
/**
 * Profile API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateProfileRequestUpdatedProfile } from './UpdateProfileRequestUpdatedProfile';
import {
    UpdateProfileRequestUpdatedProfileFromJSON,
    UpdateProfileRequestUpdatedProfileFromJSONTyped,
    UpdateProfileRequestUpdatedProfileToJSON,
} from './UpdateProfileRequestUpdatedProfile';

/**
 * 
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    userId?: string;
    /**
     * 
     * @type {UpdateProfileRequestUpdatedProfile}
     * @memberof UpdateProfileRequest
     */
    updatedProfile?: UpdateProfileRequestUpdatedProfile;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): value is UpdateProfileRequest {
    return true;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'updatedProfile': json['updatedProfile'] == null ? undefined : UpdateProfileRequestUpdatedProfileFromJSON(json['updatedProfile']),
    };
}

export function UpdateProfileRequestToJSON(value?: UpdateProfileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'updatedProfile': UpdateProfileRequestUpdatedProfileToJSON(value['updatedProfile']),
    };
}

