/* tslint:disable */
/* eslint-disable */
/**
 * Profile API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfile200Response
 */
export interface UpdateProfile200Response {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the UpdateProfile200Response interface.
 */
export function instanceOfUpdateProfile200Response(value: object): value is UpdateProfile200Response {
    return true;
}

export function UpdateProfile200ResponseFromJSON(json: any): UpdateProfile200Response {
    return UpdateProfile200ResponseFromJSONTyped(json, false);
}

export function UpdateProfile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfile200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UpdateProfile200ResponseToJSON(value?: UpdateProfile200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

