/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PutHealthUserProfileRequest } from '../model';
// @ts-ignore
import type { UserProfileResponse } from '../model';
/**
 * OpenCdxhealthUserRestControllerApi - axios parameter creator
 * @export
 */
export const OpenCdxhealthUserRestControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Retrieve User Profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealthUserProfile: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/profile/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the user profile information.
         * @summary Update User Profile
         * @param {PutHealthUserProfileRequest} putHealthUserProfileRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putHealthUserProfile: async (putHealthUserProfileRequest: PutHealthUserProfileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'putHealthUserProfileRequest' is not null or undefined
            assertParamExists('putHealthUserProfile', 'putHealthUserProfileRequest', putHealthUserProfileRequest)
            const localVarPath = `/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putHealthUserProfileRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenCdxhealthUserRestControllerApi - functional programming interface
 * @export
 */
export const OpenCdxhealthUserRestControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OpenCdxhealthUserRestControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Retrieve User Profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHealthUserProfile(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHealthUserProfile(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenCdxhealthUserRestControllerApi.getHealthUserProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the user profile information.
         * @summary Update User Profile
         * @param {PutHealthUserProfileRequest} putHealthUserProfileRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putHealthUserProfile(putHealthUserProfileRequest: PutHealthUserProfileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putHealthUserProfile(putHealthUserProfileRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenCdxhealthUserRestControllerApi.putHealthUserProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OpenCdxhealthUserRestControllerApi - factory interface
 * @export
 */
export const OpenCdxhealthUserRestControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OpenCdxhealthUserRestControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary Retrieve User Profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealthUserProfile(options?: RawAxiosRequestConfig): AxiosPromise<UserProfileResponse> {
            return localVarFp.getHealthUserProfile(options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the user profile information.
         * @summary Update User Profile
         * @param {OpenCdxhealthUserRestControllerApiPutHealthUserProfileRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putHealthUserProfile(requestParameters: OpenCdxhealthUserRestControllerApiPutHealthUserProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.putHealthUserProfile(requestParameters.putHealthUserProfileRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for putHealthUserProfile operation in OpenCdxhealthUserRestControllerApi.
 * @export
 * @interface OpenCdxhealthUserRestControllerApiPutHealthUserProfileRequest
 */
export interface OpenCdxhealthUserRestControllerApiPutHealthUserProfileRequest {
    /**
     * 
     * @type {PutHealthUserProfileRequest}
     * @memberof OpenCdxhealthUserRestControllerApiPutHealthUserProfile
     */
    readonly putHealthUserProfileRequest: PutHealthUserProfileRequest
}

/**
 * OpenCdxhealthUserRestControllerApi - object-oriented interface
 * @export
 * @class OpenCdxhealthUserRestControllerApi
 * @extends {BaseAPI}
 */
export class OpenCdxhealthUserRestControllerApi extends BaseAPI {
    /**
     * 
     * @summary Retrieve User Profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenCdxhealthUserRestControllerApi
     */
    public getHealthUserProfile(options?: RawAxiosRequestConfig) {
        return OpenCdxhealthUserRestControllerApiFp(this.configuration).getHealthUserProfile(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the user profile information.
     * @summary Update User Profile
     * @param {OpenCdxhealthUserRestControllerApiPutHealthUserProfileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenCdxhealthUserRestControllerApi
     */
    public putHealthUserProfile(requestParameters: OpenCdxhealthUserRestControllerApiPutHealthUserProfileRequest, options?: RawAxiosRequestConfig) {
        return OpenCdxhealthUserRestControllerApiFp(this.configuration).putHealthUserProfile(requestParameters.putHealthUserProfileRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

