/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ANFStatement } from './anfstatement';

/**
 * 
 * @export
 * @interface AnfStatementConnector
 */
export interface AnfStatementConnector {
    /**
     * 
     * @type {ANFStatement}
     * @memberof AnfStatementConnector
     */
    'anfStatement'?: ANFStatement;
    /**
     * 
     * @type {string}
     * @memberof AnfStatementConnector
     */
    'anfStatementType'?: AnfStatementType;
    /**
     * 
     * @type {string}
     * @memberof AnfStatementConnector
     */
    'anfOperatorType'?: AnfOperatorType;
    /**
     * 
     * @type {string}
     * @memberof AnfStatementConnector
     */
    'operatorValue'?: string;
}

export const AnfStatementType = {
    AnfStatementTypeUnspecified: 'ANF_STATEMENT_TYPE_UNSPECIFIED',
    AnfStatementTypeMain: 'ANF_STATEMENT_TYPE_MAIN',
    AnfStatementTypeAssociated: 'ANF_STATEMENT_TYPE_ASSOCIATED',
    AnfStatementUserQuestion: 'ANF_STATEMENT_USER_QUESTION',
    AnfStatementTypeNotApplicable: 'ANF_STATEMENT_TYPE_NOT_APPLICABLE',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type AnfStatementType = typeof AnfStatementType[keyof typeof AnfStatementType];
export const AnfOperatorType = {
    AnfOperatorTypeUnspecified: 'ANF_OPERATOR_TYPE_UNSPECIFIED',
    AnfOperatorTypeEqual: 'ANF_OPERATOR_TYPE_EQUAL',
    AnfOperatorTypeNotEqual: 'ANF_OPERATOR_TYPE_NOT_EQUAL',
    AnfOperatorTypeGreaterThan: 'ANF_OPERATOR_TYPE_GREATER_THAN',
    AnfOperatorTypeGreaterThanOrEqual: 'ANF_OPERATOR_TYPE_GREATER_THAN_OR_EQUAL',
    AnfOperatorTypeLessThan: 'ANF_OPERATOR_TYPE_LESS_THAN',
    AnfOperatorTypeLessThanOrEqual: 'ANF_OPERATOR_TYPE_LESS_THAN_OR_EQUAL',
    AnfOperatorTypeContains: 'ANF_OPERATOR_TYPE_CONTAINS',
    AnfOperatorTypeNotContains: 'ANF_OPERATOR_TYPE_NOT_CONTAINS',
    AnfOperatorTypeIn: 'ANF_OPERATOR_TYPE_IN',
    AnfOperatorTypeNotIn: 'ANF_OPERATOR_TYPE_NOT_IN',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type AnfOperatorType = typeof AnfOperatorType[keyof typeof AnfOperatorType];


