/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiagnosisCode } from './diagnosis-code';
// May contain unused imports in some cases
// @ts-ignore
import type { TestKit } from './test-kit';
// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface Classification
 */
export interface Classification {
    /**
     * 
     * @type {TestKit}
     * @memberof Classification
     */
    'testKit'?: TestKit;
    /**
     * 
     * @type {number}
     * @memberof Classification
     */
    'confidence'?: number;
    /**
     * 
     * @type {number}
     * @memberof Classification
     */
    'positiveProbability'?: number;
    /**
     * 
     * @type {string}
     * @memberof Classification
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof Classification
     */
    'availability'?: string;
    /**
     * 
     * @type {number}
     * @memberof Classification
     */
    'cost'?: number;
    /**
     * 
     * @type {string}
     * @memberof Classification
     */
    'furtherActions'?: string;
    /**
     * 
     * @type {Array<TestKit>}
     * @memberof Classification
     */
    'alternativeOptions'?: Array<TestKit>;
    /**
     * 
     * @type {string}
     * @memberof Classification
     */
    'feedbackUrl'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof Classification
     */
    'timestamp'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof Classification
     */
    'patientId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Classification
     */
    'notifyCdc'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Classification
     */
    'type'?: ClassificationType;
    /**
     * 
     * @type {DiagnosisCode}
     * @memberof Classification
     */
    'diagnosis'?: DiagnosisCode;
}

export const ClassificationType = {
    UnspecifiedClassificationType: 'UNSPECIFIED_CLASSIFICATION_TYPE',
    Bacterial: 'BACTERIAL',
    Viral: 'VIRAL',
    Injury: 'INJURY',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type ClassificationType = typeof ClassificationType[keyof typeof ClassificationType];


