/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Interpretation } from './interpretation';

/**
 * 
 * @export
 * @interface TestKit
 */
export interface TestKit {
    /**
     * 
     * @type {string}
     * @memberof TestKit
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestKit
     */
    'targetDisease'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestKit
     */
    'specimenType'?: SpecimenType;
    /**
     * 
     * @type {string}
     * @memberof TestKit
     */
    'procedure'?: string;
    /**
     * 
     * @type {Interpretation}
     * @memberof TestKit
     */
    'interpretationGuide'?: Interpretation;
    /**
     * 
     * @type {string}
     * @memberof TestKit
     */
    'brand'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestKit
     */
    'approvalStatus'?: string;
    /**
     * 
     * @type {number}
     * @memberof TestKit
     */
    'accuracy'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestKit
     */
    'testDuration'?: number;
    /**
     * 
     * @type {string}
     * @memberof TestKit
     */
    'testCaseId'?: string;
}

export const SpecimenType = {
    SpecimenTypeUnspecified: 'SPECIMEN_TYPE_UNSPECIFIED',
    SpecimenTypeBlood: 'SPECIMEN_TYPE_BLOOD',
    SpecimenTypeUrine: 'SPECIMEN_TYPE_URINE',
    SpecimenTypeSaliva: 'SPECIMEN_TYPE_SALIVA',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type SpecimenType = typeof SpecimenType[keyof typeof SpecimenType];


