/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Coding
 */
export interface Coding {
    /**
     * 
     * @type {string}
     * @memberof Coding
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Coding
     */
    'system'?: string;
    /**
     * 
     * @type {string}
     * @memberof Coding
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof Coding
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof Coding
     */
    'display'?: string;
}

