/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Measure } from './measure';

/**
 * 
 * @export
 * @interface Repetition
 */
export interface Repetition {
    /**
     * 
     * @type {Measure}
     * @memberof Repetition
     */
    'periodStart'?: Measure;
    /**
     * 
     * @type {Measure}
     * @memberof Repetition
     */
    'periodDuration'?: Measure;
    /**
     * 
     * @type {Measure}
     * @memberof Repetition
     */
    'eventFrequency'?: Measure;
    /**
     * 
     * @type {Measure}
     * @memberof Repetition
     */
    'eventSeparation'?: Measure;
    /**
     * 
     * @type {Measure}
     * @memberof Repetition
     */
    'eventDuration'?: Measure;
}

