/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Pagination } from './pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { UserQuestionnaireData } from './user-questionnaire-data';

/**
 * 
 * @export
 * @interface UserQuestionnaireDataResponse
 */
export interface UserQuestionnaireDataResponse {
    /**
     * 
     * @type {Array<UserQuestionnaireData>}
     * @memberof UserQuestionnaireDataResponse
     */
    'list'?: Array<UserQuestionnaireData>;
    /**
     * 
     * @type {Pagination}
     * @memberof UserQuestionnaireDataResponse
     */
    'pagination'?: Pagination;
}

