version: '3'
services:
  dashboard:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/dashboard:${version}
    volumes:
      - ../certs:/certs
    ports:
      - "3005:3005"