/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface DeliveryTracking
 */
export interface DeliveryTracking {
    /**
     * 
     * @type {string}
     * @memberof DeliveryTracking
     */
    'trackingId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTracking
     */
    'orderId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTracking
     */
    'status'?: Status;
    /**
     * 
     * @type {Timestamp}
     * @memberof DeliveryTracking
     */
    'startDatetime'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof DeliveryTracking
     */
    'endDatetime'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTracking
     */
    'currentLocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTracking
     */
    'recipient'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeliveryTracking
     */
    'deliveryItems'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTracking
     */
    'assignedCourier'?: string;
}

export const Status = {
    InTransit: 'IN_TRANSIT',
    Delivered: 'DELIVERED',
    Canceled: 'CANCELED',
    PendingPickup: 'PENDING_PICKUP',
    OutForDelivery: 'OUT_FOR_DELIVERY',
    FailedDelivery: 'FAILED_DELIVERY',
    Returned: 'RETURNED',
    Delayed: 'DELAYED',
    OnHold: 'ON_HOLD',
    Exception: 'EXCEPTION',
    Lost: 'LOST',
    Pending: 'PENDING',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type Status = typeof Status[keyof typeof Status];


