/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdditionalService } from './additional-service';
// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { FullName } from './full-name';
// May contain unused imports in some cases
// @ts-ignore
import type { Order } from './order';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentDetails } from './payment-details';
// May contain unused imports in some cases
// @ts-ignore
import type { ServiceLevel } from './service-level';

/**
 * 
 * @export
 * @interface Shipping
 */
export interface Shipping {
    /**
     * 
     * @type {string}
     * @memberof Shipping
     */
    'id'?: string;
    /**
     * 
     * @type {FullName}
     * @memberof Shipping
     */
    'shippingName'?: FullName;
    /**
     * 
     * @type {Address}
     * @memberof Shipping
     */
    'senderAddress'?: Address;
    /**
     * 
     * @type {Address}
     * @memberof Shipping
     */
    'recipientAddress'?: Address;
    /**
     * 
     * @type {Order}
     * @memberof Shipping
     */
    'packageDetails'?: Order;
    /**
     * 
     * @type {ServiceLevel}
     * @memberof Shipping
     */
    'serviceLevel'?: ServiceLevel;
    /**
     * 
     * @type {Array<AdditionalService>}
     * @memberof Shipping
     */
    'additionalServices'?: Array<AdditionalService>;
    /**
     * 
     * @type {boolean}
     * @memberof Shipping
     */
    'requireSignature'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Shipping
     */
    'declaredValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof Shipping
     */
    'shippingVendorId'?: string;
    /**
     * 
     * @type {number}
     * @memberof Shipping
     */
    'shippingCost'?: number;
    /**
     * 
     * @type {PaymentDetails}
     * @memberof Shipping
     */
    'paymentDetails'?: PaymentDetails;
}

