/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { FullName } from './full-name';
// May contain unused imports in some cases
// @ts-ignore
import type { Order } from './order';

/**
 * 
 * @export
 * @interface ShippingRequest
 */
export interface ShippingRequest {
    /**
     * 
     * @type {Address}
     * @memberof ShippingRequest
     */
    'senderAddress'?: Address;
    /**
     * 
     * @type {FullName}
     * @memberof ShippingRequest
     */
    'shippingName'?: FullName;
    /**
     * 
     * @type {Address}
     * @memberof ShippingRequest
     */
    'recipientAddress'?: Address;
    /**
     * 
     * @type {Order}
     * @memberof ShippingRequest
     */
    'packageDetails'?: Order;
    /**
     * 
     * @type {boolean}
     * @memberof ShippingRequest
     */
    'requireSignature'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ShippingRequest
     */
    'declaredValue'?: number;
}

