/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CategoryType } from './category-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface TestCase
 */
export interface TestCase {
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'manufacturerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'vendorId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TestCase
     */
    'deviceIds'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TestCase
     */
    'numberOfTests'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof TestCase
     */
    'packagingDate'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof TestCase
     */
    'expiryDate'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'batchNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'serialNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'storageRequirements'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'userInstructions'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'limitations'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'safety'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'lidrId'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof TestCase
     */
    'created'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof TestCase
     */
    'modified'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'creator'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'modifier'?: string;
    /**
     * 
     * @type {Array<CategoryType>}
     * @memberof TestCase
     */
    'categoryType'?: Array<CategoryType>;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'qrScanCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    'sku'?: string;
}

