spring:
  cloud:
    config:
      tls:
        key-store: file:/certs/opencdx-keystore.p12
        trust-store-type: PKCS12
        key-store-type: PKCS12
        key-password: opencdx
        trust-store: file:/certs/opencdx-keystore.p12
        trust-store-password: opencdx
        enabled: 'true'
        key-store-password: opencdx
      uri: https://Config:8888
  config:
    import: configserver:https://config:8888
  application:
    name: tinkar
  profiles:
    active: managed,nats,mongo,tinkar
