/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PredictorRequest } from '../model';
// @ts-ignore
import type { PredictorResponse } from '../model';
/**
 * OpenCdxRestPredictorControllerApi - axios parameter creator
 * @export
 */
export const OpenCdxRestPredictorControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PredictorRequest} predictorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        predict: async (predictorRequest: PredictorRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'predictorRequest' is not null or undefined
            assertParamExists('predict', 'predictorRequest', predictorRequest)
            const localVarPath = `/predict`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(predictorRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenCdxRestPredictorControllerApi - functional programming interface
 * @export
 */
export const OpenCdxRestPredictorControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OpenCdxRestPredictorControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PredictorRequest} predictorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async predict(predictorRequest: PredictorRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PredictorResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.predict(predictorRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenCdxRestPredictorControllerApi.predict']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OpenCdxRestPredictorControllerApi - factory interface
 * @export
 */
export const OpenCdxRestPredictorControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OpenCdxRestPredictorControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {OpenCdxRestPredictorControllerApiPredictRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        predict(requestParameters: OpenCdxRestPredictorControllerApiPredictRequest, options?: RawAxiosRequestConfig): AxiosPromise<PredictorResponse> {
            return localVarFp.predict(requestParameters.predictorRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for predict operation in OpenCdxRestPredictorControllerApi.
 * @export
 * @interface OpenCdxRestPredictorControllerApiPredictRequest
 */
export interface OpenCdxRestPredictorControllerApiPredictRequest {
    /**
     * 
     * @type {PredictorRequest}
     * @memberof OpenCdxRestPredictorControllerApiPredict
     */
    readonly predictorRequest: PredictorRequest
}

/**
 * OpenCdxRestPredictorControllerApi - object-oriented interface
 * @export
 * @class OpenCdxRestPredictorControllerApi
 * @extends {BaseAPI}
 */
export class OpenCdxRestPredictorControllerApi extends BaseAPI {
    /**
     * 
     * @param {OpenCdxRestPredictorControllerApiPredictRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenCdxRestPredictorControllerApi
     */
    public predict(requestParameters: OpenCdxRestPredictorControllerApiPredictRequest, options?: RawAxiosRequestConfig) {
        return OpenCdxRestPredictorControllerApiFp(this.configuration).predict(requestParameters.predictorRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

