/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactInfo } from './contact-info';
// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'description'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof Organization
     */
    'foundingDate'?: Timestamp;
    /**
     * 
     * @type {Address}
     * @memberof Organization
     */
    'address'?: Address;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'website'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'industry'?: string;
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    'revenue'?: number;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'logoUrl'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Organization
     */
    'socialMediaLinks'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'missionStatement'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'visionStatement'?: string;
    /**
     * 
     * @type {Array<ContactInfo>}
     * @memberof Organization
     */
    'contacts'?: Array<ContactInfo>;
    /**
     * 
     * @type {Timestamp}
     * @memberof Organization
     */
    'created'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof Organization
     */
    'modified'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'creator'?: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    'modifier'?: string;
}

