/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Attachment } from './attachment';
// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'queueId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'eventId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'organizationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'workspaceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'smsStatus'?: SmsStatus;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'emailStatus'?: EmailStatus;
    /**
     * 
     * @type {Timestamp}
     * @memberof Notification
     */
    'timestamp'?: Timestamp;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Notification
     * @deprecated
     */
    'customData'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    'toEmail'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    'ccEmail'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    'bccEmail'?: Array<string>;
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof Notification
     */
    'emailAttachments'?: Array<Attachment>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    'toPhoneNumber'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Notification
     * @deprecated
     */
    'variables'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    'recipientsId'?: Array<string>;
    /**
     * 
     * @type {Timestamp}
     * @memberof Notification
     */
    'created'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof Notification
     */
    'modified'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'creator'?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    'modifier'?: string;
}

export const SmsStatus = {
    NotificationStatusUnspecified: 'NOTIFICATION_STATUS_UNSPECIFIED',
    NotificationStatusPending: 'NOTIFICATION_STATUS_PENDING',
    NotificationStatusSent: 'NOTIFICATION_STATUS_SENT',
    NotificationStatusFailed: 'NOTIFICATION_STATUS_FAILED',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type SmsStatus = typeof SmsStatus[keyof typeof SmsStatus];
export const EmailStatus = {
    NotificationStatusUnspecified: 'NOTIFICATION_STATUS_UNSPECIFIED',
    NotificationStatusPending: 'NOTIFICATION_STATUS_PENDING',
    NotificationStatusSent: 'NOTIFICATION_STATUS_SENT',
    NotificationStatusFailed: 'NOTIFICATION_STATUS_FAILED',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type EmailStatus = typeof EmailStatus[keyof typeof EmailStatus];


