/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'pageSize'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Pagination
     */
    'sortAscending'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Pagination
     */
    'sort'?: string;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'totalRecords'?: number;
}

