/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Pagination } from './pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { SMSTemplate } from './smstemplate';

/**
 * 
 * @export
 * @interface SMSTemplateListResponse
 */
export interface SMSTemplateListResponse {
    /**
     * 
     * @type {Pagination}
     * @memberof SMSTemplateListResponse
     */
    'pagination'?: Pagination;
    /**
     * 
     * @type {Array<SMSTemplate>}
     * @memberof SMSTemplateListResponse
     */
    'templates'?: Array<SMSTemplate>;
}

