opencdx:
  client:
    trustStore: /certs/opencdx-clients.pem
    tracing:
      enabled: true
    anf:
      server: anf
      port: 9090
    audit:
      server: audit
      port: 9090
    classification:
      server: classification
      port: 9090
    communications:
      server: communications
      port: 9090
    connected-lab:
      server: connected-lab
      port: 9090
    health:
      server: health
      port: 9090
    helloworld:
      server: helloworld
      port: 9090
    iam:
      server: iam
      port: 9090
    media:
      server: media
      port: 9090
    predictor:
      server: predictor
      port: 9090
    protector:
      server: protector
      port: 9090
    provider:
      server: provider
      port: 9090
    questionnaire:
      server: questionnaire
      port: 9090
    routine:
      server: routine
      port: 9090
    tinkar:
      server: tinkar
      port: 9090
    logistics:
      server: logistics
      port: 9090

feign:
  httpclient:
    disableSslValidation: true

spring:
  cloud:
    openfeign:
      httpclient:
        disable-ssl-validation: true
      client:
        config:
          media:
            url: https://media:8080
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            micrometer.enabled: true