/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Allergy
 */
export interface Allergy {
    /**
     * 
     * @type {string}
     * @memberof Allergy
     */
    'patientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Allergy
     */
    'nationalhealthid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Allergy
     */
    'allergen'?: string;
    /**
     * 
     * @type {string}
     * @memberof Allergy
     */
    'reaction'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Allergy
     */
    'isSevere'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Allergy
     */
    'notes'?: string;
}

