/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Demographics
 */
export interface Demographics {
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'ethnicity'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'race'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'nationality'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'timeZone'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'incomeLevel'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'maritalStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'religion'?: string;
    /**
     * 
     * @type {string}
     * @memberof Demographics
     */
    'vitalStatus'?: string;
}

