/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeIdentity
 */
export interface EmployeeIdentity {
    /**
     * 
     * @type {string}
     * @memberof EmployeeIdentity
     */
    'organizationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeIdentity
     */
    'workspaceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeIdentity
     */
    'employeeId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeIdentity
     */
    'identityVerified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmployeeIdentity
     */
    'status'?: string;
}

