/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Duration
 */
export interface Duration {
    /**
     * 
     * @type {number}
     * @memberof Duration
     */
    'duration'?: number;
    /**
     * 
     * @type {string}
     * @memberof Duration
     */
    'type'?: Type;
}

export const Type = {
    DurationTypeNotSpecified: 'DURATION_TYPE_NOT_SPECIFIED',
    DurationTypeMilliseconds: 'DURATION_TYPE_MILLISECONDS',
    DurationTypeSeconds: 'DURATION_TYPE_SECONDS',
    DurationTypeMinutes: 'DURATION_TYPE_MINUTES',
    DurationTypeHours: 'DURATION_TYPE_HOURS',
    DurationTypeDays: 'DURATION_TYPE_DAYS',
    DurationTypeWeeks: 'DURATION_TYPE_WEEKS',
    DurationTypeMonths: 'DURATION_TYPE_MONTHS',
    DurationTypeYears: 'DURATION_TYPE_YEARS',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type Type = typeof Type[keyof typeof Type];


