/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssociatedStatement } from './associated-statement';
// May contain unused imports in some cases
// @ts-ignore
import type { LogicalExpression } from './logical-expression';
// May contain unused imports in some cases
// @ts-ignore
import type { Measure } from './measure';
// May contain unused imports in some cases
// @ts-ignore
import type { Reference } from './reference';
// May contain unused imports in some cases
// @ts-ignore
import type { Repetition } from './repetition';

/**
 * 
 * @export
 * @interface RequestCircumstance
 */
export interface RequestCircumstance {
    /**
     * 
     * @type {Measure}
     * @memberof RequestCircumstance
     */
    'timing'?: Measure;
    /**
     * 
     * @type {Array<LogicalExpression>}
     * @memberof RequestCircumstance
     */
    'purpose'?: Array<LogicalExpression>;
    /**
     * 
     * @type {Array<AssociatedStatement>}
     * @memberof RequestCircumstance
     */
    'conditionalTrigger'?: Array<AssociatedStatement>;
    /**
     * 
     * @type {Array<Reference>}
     * @memberof RequestCircumstance
     */
    'requestedParticipant'?: Array<Reference>;
    /**
     * 
     * @type {LogicalExpression}
     * @memberof RequestCircumstance
     */
    'priority'?: LogicalExpression;
    /**
     * 
     * @type {Measure}
     * @memberof RequestCircumstance
     */
    'requestedResult'?: Measure;
    /**
     * 
     * @type {Repetition}
     * @memberof RequestCircumstance
     */
    'repetition'?: Repetition;
    /**
     * 
     * @type {Array<string>}
     * @memberof RequestCircumstance
     */
    'deviceId'?: Array<string>;
}

