/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageTemplate } from './message-template';
// May contain unused imports in some cases
// @ts-ignore
import type { Pagination } from './pagination';

/**
 * 
 * @export
 * @interface MessageTemplateListResponse
 */
export interface MessageTemplateListResponse {
    /**
     * 
     * @type {Array<MessageTemplate>}
     * @memberof MessageTemplateListResponse
     */
    'templates'?: Array<MessageTemplate>;
    /**
     * 
     * @type {Pagination}
     * @memberof MessageTemplateListResponse
     */
    'pagination'?: Pagination;
}

