spring:
  banner:
    location: /banner.txt
  application:
    name: Admin
  boot:
    admin:
      context-path: /admin
      ui:
        title: OpenCDX Admin
        brand: <img src="opencdx.png" style="object-fit:contain; width:125px; height:50px;"><span> Admin</span>
        theme:
          color: "#E5E6E4"
          palette:
            50: "#8A8A8A"
            100: "#949494"
            200: "#9E9F9E"
            300: "#A8A9A8"
            400: "#B3B3B2"
            500: "#BDBDBC"
            600: "#C7C7C6"
            700: "#D1D2D0"
            800: "#DBDCDA"
            900: "#E5E6E4"
        external-views:
          - label: "Discovery"
            url: "https://localhost:8761/"
          - label: "NATS"
            url: "http://localhost:8222/"
          - label: "Documentation"
            url: "https://localhost:8861//javadoc/index.html"
            children:
              - label: "Javadoc"
                url: "https://localhost:8861/javadoc/index.html"
              - label: "Protodoc"
                url: "https://localhost:8861/protodoc/index.html"
              - label: "Dependencies"
                url: "https://localhost:8861/dependency/dependency-check-report.html"
              - label: "JMeter Smoke"
                url: "https://localhost:8861/jmeter/index.html"
          - label: "Monitoring"
            url: "http://localhost:3000/d/spring_boot_21/spring-boot-2-1-system-monitor?orgId=1&refresh=5s"
            children:
              - label: "Zipkin"
                url: "https://localhost:9411/zipkin"
              - label: "Grafana"
                url: "https://localhost:3000/d/spring_boot_21/spring-boot-2-1-system-monitor?orgId=1&refresh=5s"
              - label: "Prometheus"
                url: "https://localhost:9090"
          - label: "Swagger"
            url: "https://localhost:8080/iam/swagger-ui/index.html"
            children:
              - label: "Anf"
                url: "https://localhost:8080/anf/swagger-ui/index.html"
              - label: "Audit"
                url: "https://localhost:8080/audit/swagger-ui/index.html"
              - label: "Classification"
                url: "https://localhost:8080/classification/swagger-ui/index.html"
              - label: "Communications"
                url: "https://localhost:8080/communications/swagger-ui/index.html"
              - label: "Connected Test"
                url: "https://localhost:8080/connected-test/swagger-ui/index.html"
              - label: "Health"
                url: "https://localhost:8080/health/swagger-ui/index.html"
              - label: "Logistics"
                url: "https://localhost:8080/logistics/swagger-ui/index.html"
              - label: "IAM"
                url: "https://localhost:8080/iam/swagger-ui/index.html"
              - label: "Media"
                url: "https://localhost:8080/media/swagger-ui/index.html"
              - label: "Predictor"
                url: "https://localhost:8080/predictor/swagger-ui/index.html"
              - label: "Protector"
                url: "https://localhost:8080/protector/swagger-ui/index.html"
              - label: "Questionnaire"
                url: "https://localhost:8080/questionnaire/swagger-ui/index.html"
              - label: "Routine"
                url: "https://localhost:8080/routine/swagger-ui/index.html"
              - label: "Tinkar"
                url: "https://localhost:8080/tinkar/swagger-ui/index.html"



server:
  port: 8861
  ssl:
    enabled: true
    client-auth: none
    key-store: file:/certs/opencdx-keystore.p12
    key-store-password: opencdx
    key-alias: admin

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling.probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: https://zipkin:9411/api/v2/spans

logging:
  level:
    health:
      safe: debug
  pattern:
    level: "${spring.application.name:} trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${spring.application.name:} trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: "/var/log/sample-boot-application.log"


eureka:
  client:
    service-url:
      defaultZone: https://discovery:8761/eureka/
    tls:
      enabled: 'true'
      key-store: file:/certs/opencdx-keystore.p12
      key-store-type: PKCS12
      key-store-password: opencdx
      trust-store: file:/certs/opencdx-keystore.p12
      trust-store-type: PKCS12
      trust-store-password: opencdx
      key-password: opencdx
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/