/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'countryId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'addressPurpose'?: AddressPurpose;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address1'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address2'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address3'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'postalCode'?: string;
}

export const AddressPurpose = {
    Location: 'LOCATION',
    Mailing: 'MAILING',
    Primary: 'PRIMARY',
    Secondary: 'SECONDARY',
    Billing: 'BILLING',
    Shipping: 'SHIPPING',
    Work: 'WORK',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type AddressPurpose = typeof AddressPurpose[keyof typeof AddressPurpose];


