/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CategoryType } from './category-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'model'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'manufacturerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'manufacturerCountryId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'vendorId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'vendorCountryId'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof Device
     */
    'manufactureDate'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof Device
     */
    'expiryDate'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'batchNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'serialNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'testTypeId'?: string;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    'testSensitivity'?: number;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    'testSpecificity'?: number;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'lidrId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'storageRequirements'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof Device
     */
    'testValidationDate'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'approvalStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'safety'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'userInstructions'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'limitations'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'warrantyInfo'?: string;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    'intendedUseAge'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Device
     */
    'isFdaAuthorized'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'deviceStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'associatedSoftwareVersion'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Device
     */
    'testCaseIds'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'shortDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'description'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof Device
     */
    'created'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof Device
     */
    'modified'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'creator'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'modifier'?: string;
    /**
     * 
     * @type {Array<CategoryType>}
     * @memberof Device
     */
    'categoryType'?: Array<CategoryType>;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'qrScanCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    'sku'?: string;
}

