/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentDetails
 */
export interface PaymentDetails {
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    'paymentMode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    'insuranceInfoId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    'paymentTransactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    'paymentDetails'?: string;
}

