/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryType } from './category-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactInfo } from './contact-info';
// May contain unused imports in some cases
// @ts-ignore
import type { EmailAddress } from './email-address';
// May contain unused imports in some cases
// @ts-ignore
import type { PhoneNumber } from './phone-number';
// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface Vendor
 */
export interface Vendor {
    /**
     * 
     * @type {string}
     * @memberof Vendor
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Vendor
     */
    'vendorName'?: string;
    /**
     * 
     * @type {Address}
     * @memberof Vendor
     */
    'vendorAddress'?: Address;
    /**
     * 
     * @type {ContactInfo}
     * @memberof Vendor
     */
    'vendorContact'?: ContactInfo;
    /**
     * 
     * @type {EmailAddress}
     * @memberof Vendor
     */
    'vendorEmail'?: EmailAddress;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof Vendor
     */
    'vendorPhone'?: PhoneNumber;
    /**
     * 
     * @type {string}
     * @memberof Vendor
     */
    'vendorWebsite'?: string;
    /**
     * 
     * @type {string}
     * @memberof Vendor
     */
    'vendorDescription'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Vendor
     */
    'vendorCertifications'?: Array<string>;
    /**
     * 
     * @type {Timestamp}
     * @memberof Vendor
     */
    'created'?: Timestamp;
    /**
     * 
     * @type {Timestamp}
     * @memberof Vendor
     */
    'modified'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof Vendor
     */
    'creator'?: string;
    /**
     * 
     * @type {string}
     * @memberof Vendor
     */
    'modifier'?: string;
    /**
     * 
     * @type {Array<CategoryType>}
     * @memberof Vendor
     */
    'categoryType'?: Array<CategoryType>;
}

