/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Measure
 */
export interface Measure {
    /**
     * 
     * @type {string}
     * @memberof Measure
     */
    'upperBound'?: string;
    /**
     * 
     * @type {string}
     * @memberof Measure
     */
    'lowerBound'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Measure
     */
    'includeUpperBound'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Measure
     */
    'includeLowerBound'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Measure
     */
    'semantic'?: string;
    /**
     * 
     * @type {string}
     * @memberof Measure
     */
    'resolution'?: string;
}

