/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface Repetition
 */
export interface Repetition {
    /**
     * 
     * @type {Timestamp}
     * @memberof Repetition
     */
    'periodStart'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof Repetition
     */
    'periodDuration'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repetition
     */
    'periodDurationType'?: PeriodDurationType;
    /**
     * 
     * @type {number}
     * @memberof Repetition
     */
    'eventFrequency'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repetition
     */
    'eventFrequencyType'?: EventFrequencyType;
    /**
     * 
     * @type {number}
     * @memberof Repetition
     */
    'eventSeparation'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repetition
     */
    'eventSeparationType'?: EventSeparationType;
    /**
     * 
     * @type {number}
     * @memberof Repetition
     */
    'eventDuration'?: number;
    /**
     * 
     * @type {string}
     * @memberof Repetition
     */
    'eventDurationType'?: EventDurationType;
}

export const PeriodDurationType = {
    DurationTypeNotSpecified: 'DURATION_TYPE_NOT_SPECIFIED',
    DurationTypeMilliseconds: 'DURATION_TYPE_MILLISECONDS',
    DurationTypeSeconds: 'DURATION_TYPE_SECONDS',
    DurationTypeMinutes: 'DURATION_TYPE_MINUTES',
    DurationTypeHours: 'DURATION_TYPE_HOURS',
    DurationTypeDays: 'DURATION_TYPE_DAYS',
    DurationTypeWeeks: 'DURATION_TYPE_WEEKS',
    DurationTypeMonths: 'DURATION_TYPE_MONTHS',
    DurationTypeYears: 'DURATION_TYPE_YEARS',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type PeriodDurationType = typeof PeriodDurationType[keyof typeof PeriodDurationType];
export const EventFrequencyType = {
    DurationTypeNotSpecified: 'DURATION_TYPE_NOT_SPECIFIED',
    DurationTypeMilliseconds: 'DURATION_TYPE_MILLISECONDS',
    DurationTypeSeconds: 'DURATION_TYPE_SECONDS',
    DurationTypeMinutes: 'DURATION_TYPE_MINUTES',
    DurationTypeHours: 'DURATION_TYPE_HOURS',
    DurationTypeDays: 'DURATION_TYPE_DAYS',
    DurationTypeWeeks: 'DURATION_TYPE_WEEKS',
    DurationTypeMonths: 'DURATION_TYPE_MONTHS',
    DurationTypeYears: 'DURATION_TYPE_YEARS',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type EventFrequencyType = typeof EventFrequencyType[keyof typeof EventFrequencyType];
export const EventSeparationType = {
    DurationTypeNotSpecified: 'DURATION_TYPE_NOT_SPECIFIED',
    DurationTypeMilliseconds: 'DURATION_TYPE_MILLISECONDS',
    DurationTypeSeconds: 'DURATION_TYPE_SECONDS',
    DurationTypeMinutes: 'DURATION_TYPE_MINUTES',
    DurationTypeHours: 'DURATION_TYPE_HOURS',
    DurationTypeDays: 'DURATION_TYPE_DAYS',
    DurationTypeWeeks: 'DURATION_TYPE_WEEKS',
    DurationTypeMonths: 'DURATION_TYPE_MONTHS',
    DurationTypeYears: 'DURATION_TYPE_YEARS',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type EventSeparationType = typeof EventSeparationType[keyof typeof EventSeparationType];
export const EventDurationType = {
    DurationTypeNotSpecified: 'DURATION_TYPE_NOT_SPECIFIED',
    DurationTypeMilliseconds: 'DURATION_TYPE_MILLISECONDS',
    DurationTypeSeconds: 'DURATION_TYPE_SECONDS',
    DurationTypeMinutes: 'DURATION_TYPE_MINUTES',
    DurationTypeHours: 'DURATION_TYPE_HOURS',
    DurationTypeDays: 'DURATION_TYPE_DAYS',
    DurationTypeWeeks: 'DURATION_TYPE_WEEKS',
    DurationTypeMonths: 'DURATION_TYPE_MONTHS',
    DurationTypeYears: 'DURATION_TYPE_YEARS',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type EventDurationType = typeof EventDurationType[keyof typeof EventDurationType];


