/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssociatedStatement } from './associated-statement';
// May contain unused imports in some cases
// @ts-ignore
import type { Measure } from './measure';
// May contain unused imports in some cases
// @ts-ignore
import type { Participant } from './participant';
// May contain unused imports in some cases
// @ts-ignore
import type { Repetition } from './repetition';

/**
 * 
 * @export
 * @interface RequestCircumstance
 */
export interface RequestCircumstance {
    /**
     * 
     * @type {Measure}
     * @memberof RequestCircumstance
     */
    'timing'?: Measure;
    /**
     * 
     * @type {Array<string>}
     * @memberof RequestCircumstance
     */
    'purpose'?: Array<string>;
    /**
     * 
     * @type {Array<AssociatedStatement>}
     * @memberof RequestCircumstance
     */
    'conditionalTrigger'?: Array<AssociatedStatement>;
    /**
     * 
     * @type {Array<Participant>}
     * @memberof RequestCircumstance
     */
    'requestedParticipant'?: Array<Participant>;
    /**
     * 
     * @type {string}
     * @memberof RequestCircumstance
     */
    'priority'?: Priority;
    /**
     * 
     * @type {Measure}
     * @memberof RequestCircumstance
     */
    'requestedResult'?: Measure;
    /**
     * 
     * @type {Repetition}
     * @memberof RequestCircumstance
     */
    'repetition'?: Repetition;
}

export const Priority = {
    Routine: 'ROUTINE',
    Stat: 'STAT',
    Unrecognized: 'UNRECOGNIZED'
} as const;

export type Priority = typeof Priority[keyof typeof Priority];


